// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaZVb1YO_SL3hRnAAgctRXyc7yug8CKa0',
    appId: '1:504559553465:web:70ac6355fa2db5f7878468',
    messagingSenderId: '504559553465',
    projectId: 'dtx-eye-fd2c1',
    authDomain: 'dtx-eye-fd2c1.firebaseapp.com',
    storageBucket: 'dtx-eye-fd2c1.appspot.com',
    measurementId: 'G-4LE61YDX3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJbi2DFwzdy1TJeesPmi6XzxFT4-1-Q3E',
    appId: '1:504559553465:android:f279305d4150f363878468',
    messagingSenderId: '504559553465',
    projectId: 'dtx-eye-fd2c1',
    storageBucket: 'dtx-eye-fd2c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNK0uuxR5HWPup0MvGgu1t33MFQgvHLHs',
    appId: '1:504559553465:ios:055227756fb4127a878468',
    messagingSenderId: '504559553465',
    projectId: 'dtx-eye-fd2c1',
    storageBucket: 'dtx-eye-fd2c1.appspot.com',
    iosClientId: '504559553465-593m9gd2tc3f17rland721jvlihj2l9o.apps.googleusercontent.com',
    iosBundleId: 'com.eyepatch.eyepatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNK0uuxR5HWPup0MvGgu1t33MFQgvHLHs',
    appId: '1:504559553465:ios:055227756fb4127a878468',
    messagingSenderId: '504559553465',
    projectId: 'dtx-eye-fd2c1',
    storageBucket: 'dtx-eye-fd2c1.appspot.com',
    iosClientId: '504559553465-593m9gd2tc3f17rland721jvlihj2l9o.apps.googleusercontent.com',
    iosBundleId: 'com.eyepatch.eyepatchApp',
  );
}
